version: '3.8' # Especificar a versão é uma boa prática

services:

  app:
    build: .
    container_name: api-sisman
    ports:
      - 3080:3080
    volumes:
      - .:/home/node/sisman-be
    restart: unless-stopped
    depends_on:
      - db
    networks: # <-- Conectar à rede compartilhada
      - sisman_net

  db:
    image: mariadb:11.5.2-noble
    container_name: ${DB_HOST}
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}${ENV}
    ports:
      - 3306:3306
    volumes:
    - ./.docker/mariadb:/docker-entrypoint-initdb.d
      # - ./docker/dbdata:/var/lib/mysql
    restart: unless-stopped
    networks: # <-- Conectar à rede compartilhada
      - sisman_net

      # Define a rede compartilhada
networks:
  sisman_net:
    driver: bridge # Rede padrão do tipo bridge