### Variables
@urlLocal = {{apiUrl}}/sisman-legacy
@contentType = application/json

### POST test-fetch users
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"users"}

### GET materials out
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/out/?startDate=2025-05-20&endDate=2025-05-20"}

### GET materials-items out
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/out/items"}

### Importação de materials out
POST {{urlLocal}}/import-materials-out
Content-Type: {{contentType}}

{"relativePath":"materials/out/?startDate=2025-05-20&endDate=2025-05-20"}

### Importação de materials-items out
POST {{urlLocal}}/import-materials-items-out
Content-Type: {{contentType}}

{"relativePath":"materials/out/items"}

### GET materials in
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/in/?startDate=2025-05-24&endDate=2025-09-03"}

### Importação de materials in (junto com items aninhados)
POST {{urlLocal}}/import-materials-in
Content-Type: {{contentType}}

{"relativePath":"materials/in/?startDate=2025-05-20&endDate=2025-05-20"}
