### Variables
@urlLocal = {{apiUrl}}/sisman-legacy
@contentType = application/json

### POST test-fetch users
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"users"}

### GET test-fetch
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/in/?startDate=2025-08-24&endDate=2025-09-03"}
