### Variables
@urlLocal = {{apiUrl}}/sisman-legacy
@contentType = application/json

### POST test-fetch users
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"users"}

### GET materials out
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/out/?startDate=2025-05-20&endDate=2025-05-20"}

### Importação de materials out
POST {{urlLocal}}/import-materials-out
Content-Type: {{contentType}}

{"relativePath":"materials/out/?startDate=2025-05-20&endDate=2025-05-20"}

### GET materials in
POST {{urlLocal}}/test-fetch
Content-Type: {{contentType}}

{"relativePath":"materials/in/?startDate=2025-05-24&endDate=2025-09-03"}
