### GET index
GET {{apiUrl}}

### POST index
POST {{apiUrl}}

### Test shutdown with request delay
GET {{apiUrl}}/delay

### Test error response
GET {{apiUrl}}/error-http

### Test error response
GET {{apiUrl}}/error-not-http

### GET well-known routes - security.txt
GET {{apiUrl}}/.well-known/security.txt

### GET well-known routes - security.txt
GET {{apiUrl}}/robots.txt

### GET favicon
GET {{apiUrl}}/favicon.ico