### Variables
@urlLocal = {{apiUrl}}/file
@contentType = application/json

### GET view file
# @prompt attachmentId
GET {{urlLocal}}/{{attachmentId}}/view
Authorization: Bearer {{token}}

### GET download file
# @prompt attachmentId
GET {{urlLocal}}/{{attachmentId}}/download
Authorization: Bearer {{token}}


### PUT correct images without metadata
PUT {{urlLocal}}/correct-images
Authorization: Bearer {{token}}

