### Variables
@urlLocal = {{apiUrl}}/maintenance-request
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### GET one by protocol
GET {{urlLocal}}/protocol
?value=4506/2025
Authorization: Bearer {{token}}

### GET one balance
# @prompt id
GET {{urlLocal}}/balance/{{id}}
Authorization: Bearer {{token}}

### GET one by protocol
GET {{urlLocal}}/balance/protocol
?value=4506/2025
Authorization: Bearer {{token}}

### GET deficit-status-paginated
GET {{urlLocal}}/deficit-status-paginated
?pageIndex=1
&pageSize=10
Authorization: Bearer {{token}}

### GET deficit-status
GET {{urlLocal}}/deficit-status/maintenance-instance/1
?startDate=2025-01-01T00:00:00Z
&endDate=2025-01-31T23:59:59Z
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "protocolNumber": "MANUT-{{$timestamp}}",
    "title": "Example Maintenance Request",
    "requestedAt": "2023-10-27T10:00:00.000Z",
    "deadline": "2023-11-15T17:00:00.000Z",
    "solutionDetails": "Solution provided",
    "completedAt": "2023-11-10T14:30:00.000Z",
    "createdBy": {"id": 1},
    "assignedTo": {"id": 1},
    "facilityComplex" : {"id": "1639.00236.500-5"},
    "building": {"id": "1639.00236.500-5-001"},
    "serviceType": {"id": 1},
    "createdBy": {"id": 1},
    "statuses": {"status": "PENDING"}
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "protocolNumber": "MANUT-{{$timestamp}}",
    "title": "Example Maintenance Request",
    "requestedAt": "2023-10-27T10:00:00.000Z",
    "deadline": "2023-11-15T17:00:00.000Z",
    "solutionDetails": "Solution provided",
    "completedAt": "2023-11-10T14:30:00.000Z",
    "createdBy": {"id": 1},
    "assignedTo": {"id": 1},
    "facilityComplex" : {"id": "1639.00236.500-5"},
    "building": {"id": "1639.00236.500-5-001"},
    "serviceType": {"id": 1},
    "currentMaintenanceInstance": {"id": 1},
    "createdBy": {"id": 1},
    "statuses": {"status": "PENDING"},
    "materialRequests": [
        {
            "protocolNumber": "6433/2024"
        }
    ]
}

### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "title": "Updated Maintenance Request Title",
    "description": "Updated details of the maintenance request",
    "statuses": {"status": "PENDING"}
}

### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
