### Variables
@urlLocal = {{apiUrl}}/material-request
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET all
GET {{urlLocal}}
?startDate=2025-01-01T00:00:00Z
&endDate=2025-12-31T23:59:59Z
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### GET one by protocol
GET {{urlLocal}}/protocol
?value=29883/2025
Authorization: Bearer {{token}}

### GET balance by protocol
GET {{urlLocal}}/balance/protocol
?value=29883/2025
Authorization: Bearer {{token}}

### GET one balance
# @prompt id
GET {{urlLocal}}/balance/{{id}}
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "protocolNumber": "REQ-{{$timestamp}}",
    "requestType": "NEW_MATERIALS",
    "justification": "Example material request",
    "origin": "SISMAN",
    "requestValue": 100.50,
    "servedValue": 0,
    "storage": {"id": 1}
}

### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "justification": "Updated justification",
    "servedValue": 100.50
}

### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
