### Variables
@urlLocal = {{apiUrl}}/material-stock-movement
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "quantity": 60,
    "unitPrice": 15.50,
    "globalMaterial": {"id": "302400026280"},
    "warehouse": {"id": 1},
    "movementType": {"code": "IN_CENTRAL"},
    "processedByUser": {"id": 1},
    "collectedByUser": {"id": 1},
    "materialRequestItem": {"id": 217},
    "maintenanceRequest": {"id": 41}
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "quantity": 50,
    "globalMaterial": {"id": "302400026280"},
    "warehouse": {"id": 1},
    "movementType": {"code": "INITIAL_STOCK_LOAD"},
    "processedByUser": {"id": 1}
}

### POST
POST {{urlLocal}}/count
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "quantity": 50,
    "globalMaterial": {"id": "3026000000032"},
    "warehouse": {"id": 1},
    "processedByUser": {"id": 1}
}


### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "quantity": 12.0
}


### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
