### Variables
@urlLocal = {{apiUrl}}/material-receipt
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "receiptNumber": "REC-013",
    "receiptDate": "2024-07-25T10:00:00Z",
    "movementType": {
        "code": "IN_CENTRAL"
    },
    "destinationWarehouse": {
        "id": 1
    },
    "processedByUser": {
        "id": 1
    },
    "items": [
        {
            "materialId": "302400023848",
            "quantityExpected": 2,
            "quantityReceived": 2,
            "quantityAccepted": 2,
            "quantityRejected": 0,
            "unitPrice": 1.62,
            "unitOfMeasure": "UN",
            "materialRequestItemId": 238
        }
    ],
    "materialRequest": {
        "id": 222
    }
}


### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "receiptNumber": "REC-001-UPDATED"
}


### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
