### Variables
@urlLocal = {{apiUrl}}/material-restriction-order
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "restrictionOrderNumber": "REST-{{$timestamp}}",
    "warehouse": {
        "id": 1
    },
    "processedByUser": {"id": 1},
    "processedAt": "2024-07-25T10:00:00Z",
    "targetMaterialRequest": {
        "id": 337
    },
    "notes": "Restrição de materiais para o pedido X.",
    "items": [
        {
            "globalMaterialId": "302400002280",
            "quantityRestricted":1,
            "targetMaterialRequestItemId": 496
        }
    ]
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "restrictionOrderNumber": "REST-014",
    "warehouse": {
        "id": 1
    },
    "processedByUser": {"id": 1},
    "processedAt": "2024-07-25T10:00:00Z",
    "targetMaterialRequest": {
        "id": 424
    },
        "items": [
        {
            "globalMaterialId": "3026000000032",
            "quantityRestricted":50,
            "targetMaterialRequestItemId": 789
        }
    ],
    "notes": "Restrição de materiais para o pedido X."
}
### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "restrictionOrderNumber": "REST-{{$timestamp}}",
    "warehouse": {
        "id": 1
    },
    "processedByUser": {"id": 1},
    "processedAt": "2024-07-25T10:00:00Z",
    "targetMaterialRequest": {
        "id": 322
    },
        "items": [
        {
            "globalMaterialId": "302400030155",
            "quantityRestricted":50,
            "targetMaterialRequestItemId": 469
        }
    ],
    "notes": "Restrição de materiais para o pedido X."
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "restrictionOrderNumber": "REST-013",
    "warehouse": {
        "id": 1
    },
    "processedByUser": {"id": 1},
    "processedAt": "2024-07-25T10:00:00Z",
    "targetMaterialRequest": {
        "id": 424
    },
    "notes": "Restrição de materiais para o pedido X.",
    "status": "FULLY_RESTRICTED"
}


### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "notes": "Restrição atualizada com novas observações1.",
        "items": [
        {
            "id": 2,
            "globalMaterialId": "3026000000032",
            "quantityRestricted":60,
            "targetMaterialRequestItemId": 789
        }
    ]
}

### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
        "items": [
        {
            "id": 1,
            "globalMaterialId": "302400030155",
            "quantityRestricted":5,
            "targetMaterialRequestItemId": 469
        }
    ],
    "notes": "Restrição de materiais para o pedido X123."
}

### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "notes": "Restrição atualizada com novas observações.",
    "status": "FREE"
}


### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
