### Variables
@urlLocal = {{apiUrl}}/material-withdrawal
@contentType = application/json

### GET all
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET all by warehouse
GET {{urlLocal}}/warehouse/1
Authorization: Bearer {{token}}

### GET all by warehouse with rangeDate
GET {{urlLocal}}/warehouse/1
?startDate=2025-01-01T00:00:00Z
&endDate=2025-12-31T23:59:59Z
&movementSubTypeCode=OUT_CENTRAL
Authorization: Bearer {{token}}

### GET one
# @prompt id
GET {{urlLocal}}/{{id}}
Authorization: Bearer {{token}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "withdrawalNumber": "RET-{{$timestamp}}",
    "withdrawalDate": "2024-07-25T10:00:00Z",
    "warehouse": {
        "id": 1
    },
    "processedByUser": {
        "id": 1
    },
    "authorizedByUser": {
        "id": 1
    },
    "collectedByWorker": {
    "id": 1
    },
    "movementType": {
        "code": "OUT_SERVICE_USAGE"
    },
    "items": [
        {
            "globalMaterialId": "3028000000047",
            "quantityWithdrawn": 2,
            "unitPrice": 2.35
        }
    ]
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "withdrawalNumber": "RET-105",
    "withdrawalDate": "2024-07-25T10:00:00Z",
    "maintenanceRequest": {"id": 43},
    "warehouse": {
        "id": 1
    },
    "processedByUser": {
        "id": 3
    },
    "collectedByWorker": {
    "id": 1
    },
    "movementType": {
        "code": "OUT_SERVICE_USAGE"
    },
    "items": [
        {
            "globalMaterialId": "3024000000161",
            "quantityWithdrawn": 1,
            "materialRequestItemId": 222,
            "unitPrice": 0.05
        }
    ],
    "materialRequest": {
        "id": 216
    }
}
### POST
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "withdrawalNumber": "RET-{{$timestamp}}",
    "withdrawalDate": "2024-07-25T10:00:00Z",
    "maintenanceRequest": {"id": 176},
    "warehouse": {
        "id": 1
    },
    "processedByUser": {
        "id": 1
    },
    "collectedByWorker": {
    "id": 1
    },
    "movementType": {
        "code": "OUT_SERVICE_USAGE"
    },
    "items": [
        {
            "globalMaterialId": "302400030155",
            "quantityWithdrawn": 20,
            "materialRequestItemId": 469
        }
    ],
    "materialRequest": {
        "id": 322
    }
}


### PUT
# @prompt id
PUT {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "withdrawalNumber": "RET-001-UPDATED"
}


### DELETE one
# @prompt id
DELETE {{urlLocal}}/{{id}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### POST verify-integrity
POST {{urlLocal}}/adm/verify-withdrawals-integrity
Content-Type: {{contentType}}
Authorization: Bearer {{token}}