### Variables
@urlLocal = {{apiUrl}}/sipac/requisicoes-manutencoes
@contentType = application/json

### GET findAll requisicoes manutencao
GET {{urlLocal}}

### GET fetch requisicoes manutencao
GET {{urlLocal}}/list/test
?dataInicial=01/01/2025
&dataFinal=15/01/2025

### POST
POST {{urlLocal}}/list/fetch-one
Content-Type: {{contentType}}

{
    "numeroAno": "2068/2023"
}

### POST
POST {{urlLocal}}/list/sync-one
Content-Type: {{contentType}}

{
    "numeroAno": "211/2025"
}

### POST
POST {{urlLocal}}/list/sync-many
Content-Type: {{contentType}}

{
    "numeroAnoArray": ["211/2025","3984/2025","5585/2025", "4445/2025" ]
}

### GET fetch and persist requisicoes manutencao
GET {{urlLocal}}/list/sync-all
?dataInicial=01/01/2025
&dataFinal=05/01/2025x


### GET fetch one and return by id
GET {{urlLocal}}/fetch-one/2043649


### POST
POST {{urlLocal}}/fetch-one-complete-and-persist
Content-Type: {{contentType}}

{
    "numeroAno": "2124/2025"
}

### POST
POST {{urlLocal}}/fetch-many-complete-and-persist
Content-Type: {{contentType}}

{
    "numeroAnoArray": [
  "3797/2025", "3798/2025", "3799/2025", "3800/2025", "3801/2025",
  "3803/2025", "3804/2025", "3805/2025", "3806/2025", "3807/2025",
  "3808/2025", "3809/2025", "3811/2025", "3812/2025", "3813/2025",
  "3814/2025", "3815/2025", "3818/2025", "3819/2025", "3820/2025",
  "3821/2025", "3822/2025", "3823/2025", "3825/2025", "3826/2025",
  "3827/2025", "3828/2025", "3829/2025", "3830/2025", "3831/2025"
]
}