### Variables
@urlLocal = {{apiUrl}}/sipac
@contentType = application/json


### GET materiais
GET {{urlLocal}}/materiais

### GET one material by code
GET {{urlLocal}}/materiais/300700000086

### POST
POST {{urlLocal}}/materiais/sync-many
Content-Type: {{contentType}}

{
    "codigos": ["300700000086","300700000116","300700000221"]
}

### GET and SYNC all materiais to server database
GET {{urlLocal}}/materiais/sync-all

### GET and SYNC all materiais to server database
GET {{urlLocal}}/grupos-materiais/sync-all

### GET and SYNC all materiais to server database
GET {{urlLocal}}/subgrupos-materiais/sync-all

### GET materiais
GET {{urlLocal}}/requisicoes-materiais

### GET materiais
GET {{urlLocal}}/requisicoes-materiais/list/sync-all
?dataInicial=01/01/2023
&dataFinal=31/03/2023

### POST
POST {{urlLocal}}/requisicoes-materiais/list/sync-one
Content-Type: {{contentType}}

{
    "numeroAno": "12751/2025"
}

### POST
POST {{urlLocal}}/requisicoes-materiais/list/sync-many
Content-Type: {{contentType}}

{
    "numeroAnoArray": ["12851/2025","12852/2025","12853/2025"]
}

### PUT
PUT {{urlLocal}}/requisicoes-materiais/2141648
Content-Type: {{contentType}}

