### Variables
@urlLocal = {{apiUrl}}/sipac
@contentType = application/json


### GET materiais
GET {{urlLocal}}/materiais

### GET one material by code
GET {{urlLocal}}/materiais/300700000086

### POST
POST {{urlLocal}}/materiais/sync-many
Content-Type: {{contentType}}

{
    "codigos": ["300700000086","300700000116","300700000221"]
}

### GET and SYNC all materiais to server database
GET {{urlLocal}}/materiais/sync-all

### GET and SYNC all materiais to server database
GET {{urlLocal}}/grupos-materiais/sync-all

### GET and SYNC all materiais to server database
GET {{urlLocal}}/subgrupos-materiais/sync-all

### GET materiais
GET {{urlLocal}}/requisicoes-materiais

### GET materiais
GET {{urlLocal}}/requisicoes-materiais/list/sync-all
?dataInicial=31/03/2023
&dataFinal=31/12/2023

### POST
POST {{urlLocal}}/requisicoes-materiais/list/sync-one
Content-Type: {{contentType}}

{
    "numeroAno": "12751/2025"
}

### POST
POST {{urlLocal}}/requisicoes-materiais/list/fetch-one
Content-Type: {{contentType}}

{
    "numeroAno": "16708/2024"
}

### POST
POST {{urlLocal}}/requisicoes-materiais/list/sync-many
Content-Type: {{contentType}}

{
    "numeroAnoArray": ["12851/2025","12852/2025","12853/2025"]
}

### GET
GET {{urlLocal}}/requisicoes-materiais/fetch-one/2113090
Content-Type: {{contentType}}

### PUT
PUT {{urlLocal}}/requisicoes-materiais/2032630
Content-Type: {{contentType}}

### POST
POST {{urlLocal}}/requisicoes-materiais/fetch-one-complete
Content-Type: {{contentType}}

{
    "numeroAno": "16708/2024"
}

### POST
POST {{urlLocal}}/requisicoes-materiais/fetch-one-complete-and-persist
Content-Type: {{contentType}}

{
    "numeroAno": "16708/2024"
}

### POST
POST {{urlLocal}}/requisicoes-materiais/fetch-many-complete-and-persist
Content-Type: {{contentType}}

{
    "numeroAnoArray": [
    "16347/2025",
    "16321/2025",
    "16343/2025",
    "16455/2025",
    "16435/2025",
    "16466/2025",
    "16422/2025",
    "16421/2025",
    "16470/2025",
    "16155/2025",
    "16351/2025",
    "16544/2025",
    "16538/2025",
    "16059/2025",
    "16284/2025",
    "16385/2025",
    "16089/2025",
    "15543/2025",
    "16556/2025",
    "15052/2025",
    "16534/2025",
    "14741/2025",
    "14851/2025",
    "14522/2025",
    "16542/2025",
    "16550/2025",
    "16559/2025",
    "16626/2025",
    "16541/2025",
    "16658/2025",
    "16657/2025",
    "16655/2025",
    "16641/2025",
    "16654/2025",
    "16640/2025",
    "16668/2025",
    "16649/2025",
    "16650/2025",
    "16648/2025",
    "16646/2025",
    "16756/2025",
    "16744/2025",
    "16736/2025",
    "16751/2025",
    "16692/2025",
    "16685/2025",
    "16038/2025",
    "16669/2025",
    "16688/2025",
    "16702/2025",
    "16831/2025",
    "16700/2025",
    "16687/2025",
    "16762/2025",
    "16681/2025",
    "15609/2025",
    "15787/2025",
    "16695/2025",
    "14212/2025",
    "16764/2025",
    "16656/2025"
]
}

### POST
POST {{urlLocal}}/requisicoes-materiais/fetch-many-complete-and-persist
Content-Type: {{contentType}}

{
    "numeroAnoArray": [
    "16708/2024"
    ]
}