### Variables
@urlLocal = {{apiUrl}}/survey-response
@contentType = application/json

### GET all surveys-response
GET {{urlLocal}}
Authorization: Bearer {{token}}

### GET all surveys-response with query params
GET {{urlLocal}}
?someParam=someValue
Authorization: Bearer {{token}}

### GET one survey-response
# @prompt surveyId
GET {{urlLocal}}/{{surveyId}}
Authorization: Bearer {{token}}

### POST create survey-response WITH RELATIONS (Sem Opções)
# @prompt surveyId
# @prompt userId ID do usuário
# @prompt idQuestion1 ID da pergunta 1
# @prompt idQuestion2 ID da pergunta 2
POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "surveyId": "{{surveyId}}",
    "userId": "{{userId}}",
    "answers": [
        {
            "questionId": "{{idQuestion1}}",
            "value": 5
        },
        {
            "questionId": "{{idQuestion2}}",
            "value": "Bom"
        }
    ]
}


### POST create survey-response WITH RELATIONS (Com Opções)
# @prompt surveyId
# @prompt userId ID do usuário
# @prompt idQuestion1 ID da pergunta 1
# @prompt questionOptionId1 ID da opção da pergunta 1
# @prompt idQuestion2 ID da pergunta 2

POST {{urlLocal}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "surveyId": "{{surveyId}}",
    "userId": "{{userId}}",
    "answers": [
        {
            "questionId": "{{idQuestion1}}",
            "value": ["{{questionOptionId1}}"]
        },
        {
            "questionId": "{{idQuestion2}}",
            "value": 5
        }
    ]
}
